apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-namespace-creator-role-binding
subjects:
- kind: ServiceAccount
  name: argocd-server   # This is the default service account for ArgoCD, adjust if you're using a different one.
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-namespace-creator-role
  apiGroup: rbac.authorization.k8s.io
